spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud_order?serverTimezone=UTC
      username: root
      password: root
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  type-aliases-package: com.eagle.user.domain
server:
  port: 8080
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/